[package]
name = "lol-companion"
version = "0.1.2"
description = "League of Legends companion overlay shell"
authors = ["liudan"]
edition = "2021"

[lib]
name = "lol_companion_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[target.'cfg(target_os = "windows")'.dependencies]
sysinfo = { version = "0.39.3", default-features = false, features = ["system"] }
